version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - APP_ENV=dev
      - APP_FRONTEND_PORT=3000
    ports:
      - "3000:3000"
    container_name: frontend
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
